import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  app: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  content: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  header: {
    marginLeft: 10,
    marginBottom: 5,
  },
  date: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
    marginTop: 25,
    marginHorizontal: 15,
    backgroundColor: '#ffffff',
    padding: 15,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statItem: {
    alignItems: 'center',
  },
  statLabel: {
    marginLeft: 10,
    marginRight: 10,
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  illustrationContainer: {
    alignItems: 'center',
    marginBottom: 2,
    height: 300,
    backgroundColor: '#ECFFDC',
    borderRadius: 20,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 15,
    elevation: 4,
  },
  illustrationImage: {
    width: '85%',
    height: '85%',
    resizeMode: 'contain',
  },
  welcomeCard: {
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 12,
    marginTop: 25,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  welcomeTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 8,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: '#666',
  },
  upcomingCard: {
    backgroundColor: '#ECFFDC',
    padding: 20,
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  upcomingTitle: {
    fontSize: 14,
    color: '#333',
  },
  upcomingTime: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ff4444',
  },
  actionButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 0,
    marginBottom: 20,
  },
  actionButton: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 18,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minWidth: 0,
    alignItems: 'center',
    marginHorizontal: 0,
    marginLeft: 8,
  },
  actionButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  studyCard: {
    backgroundColor: '#ECFFDC',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  studyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  studyTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
  },
  studyProgress: {
    fontSize: 13,
    color: '#222',
    fontWeight: '500',
    marginLeft: 2,
  },
  studyInfo: {
    gap: 8,
  },
  participantsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  participant: {
    fontSize: 20,
    marginRight: 8,
  },
  addParticipantButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addParticipant: {
    fontSize: 16,
    color: '#666',
    lineHeight: 24,
  },
  nextMeeting: {
    fontSize: 13,
    color: '#666',
  },
  createForm: {
    backgroundColor: '#ECFFDC',
    padding: 20,
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  formTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    color: '#333',
    marginBottom: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  dropdown: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  dropdownText: {
    fontSize: 14,
    color: '#999',
  },
  dropdownArrow: {
    fontSize: 12,
    color: '#666',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    paddingBottom: 10,
    paddingTop: 5,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
  },
  activeTabButton: {
    // 활성 탭 스타일은 텍스트 색상으로 처리
  },
  tabButtonText: {
    fontSize: 12,
    color: '#666',
  },
  activeTabButtonText: {
    color: '#222',
    fontWeight: 'bold',
  },
  dashboardContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  bottomContent: {
    paddingHorizontal: 20,
    marginBottom: 20,
    position: 'absolute',
    bottom: 5,
    left: 0,
    right: 0,
  },
  divider: {
    height: 1,
    backgroundColor: '#ddd',
    width: '100%',
    marginVertical: 10,
  },
  scheduleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  scheduleText: {
    fontSize: 14,
    color: '#333',
    marginTop: 5,
    marginRight: 10,
  },
  scheduleText1: {
    fontSize: 14,
    color: 'red',
    marginTop: 5,
    marginRight: 10,
  },
  scheduleTime: {
    fontSize: 14,
    color: '#ff4444',
    fontWeight: 'bold',
    marginTop: 5,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  centerModalContent: {
    backgroundColor: '#ffffff',
    width: '100%',
    maxWidth: 500,
    borderRadius: 24,
    paddingTop: 25,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 25,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1a1a1a',
    letterSpacing: -0.5,
  },
  closeButtonContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f8f8f8',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  closeButton: {
    fontSize: 18,
    color: '#666',
    fontWeight: '500',
  },
  searchModalContent: {
    maxWidth: 440,
    paddingTop: 20,
  },
  searchContainer: {
    padding: 24,
    paddingTop: 0,
  },
  searchLabel: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    marginBottom: 16,
  },
  searchTypeContainer: {
    flexDirection: 'row',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  searchTypeButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 8,
  },
  searchTypeActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  searchTypeText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  searchTypeTextActive: {
    color: '#4CAF50',
    fontWeight: '600',
  },
  searchInputContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  searchInput: {
    flex: 1,
    height: 50,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    backgroundColor: '#fff',
    color: '#333',
  },
  searchButton: {
    backgroundColor: '#000000',
    borderRadius: 12,
    paddingHorizontal: 24,
    justifyContent: 'center',
    alignItems: 'center',
    height: 50,
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  searchButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  studyListSection: {
    marginTop: -10,
    marginHorizontal: 0,
    flex: 1,
  },
  studyListContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginHorizontal: -12,
    flex: 1,
  },
  studyListItem: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: '#ffffff',
    marginBottom: 8,
    marginHorizontal: 12,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  studyItemContent: {
    gap: 12,
  },
  moreSection: {
    marginTop: 20,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    overflow: 'hidden',
    marginHorizontal: -8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  moreItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  moreItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  moreIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ECFFDC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  moreIcon: {
    fontSize: 20,
  },
  moreTextContainer: {
    flex: 1,
  },
  moreItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 4,
  },
  moreItemSubtitle: {
    fontSize: 13,
    color: '#666',
  },
  moreArrow: {
    fontSize: 24,
    color: '#ccc',
    marginLeft: 8,
  },
  noResultContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noResultText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  createModalContent: {
    width: '90%',
    maxWidth: 440,
    maxHeight: '85%',
    backgroundColor: '#fff',
    borderRadius: 20,
    overflow: 'hidden',
  },
  createModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    marginTop: -15,
    borderBottomWidth: 1,
    borderBottomColor: 'lightgrey',
  },
  createModalTitle: {
    marginLeft: 5,
    fontSize: 18,
    fontWeight: '700',
    color: 'black',
  },
  createCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    color: 'black',
  },
  createCloseButtonText: {
    fontSize: 18,
    color: 'black',
    fontWeight: '300',
    marginTop: -2,
  },
  createFormContainer: {
    padding: 20,
  },
  createFormRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  formGroupHalf: {
    flex: 1,
    marginBottom: 0,
  },
  createFormLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
    marginBottom: 6,
  },
  createFormInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
    color: '#333',
    marginBottom: 15,
  },
  createTextArea: {
    height: 70,
    textAlignVertical: 'top',
    paddingTop: 12,
    lineHeight: 20,
  },
  createPeopleCountWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
  },
  createPeopleCountInput: {
    flex: 1,
    height: 44,
    fontSize: 14,
    color: '#333',
    padding: 0,
  },
  createPeopleCountLabel: {
    fontSize: 14,
    color: '#666',
    marginLeft: 4,
  },
  createModalFooter: {
    padding: 16,
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  createSubmitButton: {
    backgroundColor: '#4CAF50',
    borderRadius: 10,
    height: 46,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    marginTop: -30
  },
  createSubmitButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  scheduleModalContent: {
    width: '90%',
    maxWidth: 500,
    maxHeight: '80%',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingTop: 20,
  },
  scheduleList: {
    paddingHorizontal: 20,
    paddingTop: 15,
  },
  scheduleItem: {
    marginBottom: 25,
  },
  scheduleItemHeader: {
    marginBottom: 10,
  },
  dateBadge: {
    backgroundColor: '#ECFFDC',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  scheduleDate: {
    fontSize: 14,
    color: '#4CAF50',
    fontWeight: '600',
  },
  scheduleItemContent: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    padding: 2,
  },
  scheduleTimeContainer: {
    paddingHorizontal: 15,
    paddingVertical: 12,
    alignItems: 'center',
    width: 75,
  },
  scheduleTime: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  scheduleTimeLine: {
    width: 2,
    height: '70%',
    backgroundColor: '#ECFFDC',
    position: 'absolute',
    right: 0,
    top: '15%',
  },
  scheduleMainContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  scheduleInfo: {
    flex: 1,
    marginRight: 10,
  },
  scheduleItemTitle: {
    fontSize: 13,
    color: '#333',
    fontWeight: '600',
    marginBottom: 8,
  },
  scheduleMetaInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scheduleStatusBadge: {
    backgroundColor: '#FFF5E6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
  },
  scheduleStatusText: {
    fontSize: 12,
    color: '#FF9800',
    fontWeight: '500',
  },
  scheduleDuration: {
    fontSize: 13,
    color: '#666',
  },
  scheduleActionButton: {
    backgroundColor: '#4CAF50',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    shadowColor: '#4CAF50',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  scheduleActionButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  placeholderText: {
    color: '#999',
  },
  categorySelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 10,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 12,
    height: 44,
    marginTop: 5
  },
  categoryText: {
    fontSize: 13,
    color: '#333',
    flex: 1,
  },
  categoryArrow: {
    fontSize: 12,
    color: '#666',
    marginLeft: 8,
  },
  categoryContainer: {
    marginVertical: 0,
    marginHorizontal: 10,
  },
  categoryScroll: {
    paddingHorizontal: 5,
  },
  categoryButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginRight: 10,
  },
  categoryButtonActive: {
    borderBottomWidth: 2,
    borderBottomColor: '#000',
  },
  categoryButtonText: {
    fontSize: 14,
    color: '#999',
    fontWeight: '500',
  },
  categoryButtonTextActive: {
    color: '#000',
    fontWeight: '600',
  },
  sectionContainer: {
    marginVertical: 35,
    marginHorizontal: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  mainTitleContainer: {
    marginHorizontal: 20,
    marginTop: -10,
    marginBottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mainTitle: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#333',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    padding: 4,
  },
  pinkText: {
    color: '#4CAF50',
    marginTop: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  seeAllText: {
    fontSize: 14,
    color: '#ccc',
    fontWeight: '600',
  },
  recommendedScroll: {
    paddingLeft: 5,
  },
  recommendedCard: {
    width: 230,
    height: 240,
    marginRight: 15,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    overflow: 'hidden',
  },
  recommendedImage: {
    borderRadius: 20,
    width: '100%',
    height: 180,
    backgroundColor: '#f0f0f0',
  },
  locationBadge: {
    position: 'absolute',
    bottom: 70,
    left: 15,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  locationText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  recommendedTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#333',
    marginTop: 15,
    marginHorizontal: 8,
    marginBottom: 7,
  },
  hashtagContainer: {
    flexDirection: 'row',
    marginHorizontal: 8,
    marginBottom: 10,
  },
  hashtag: {
    fontSize: 11,
    color: '#000',
    marginRight: 5,
  },
  emptyCard: {
    width: 180,
    height: 120,
    borderRadius: 12,
    backgroundColor: '#f9f9f9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 15,
  },
  emptyText: {
    fontSize: 14,
    color: '#999',
  },
  categoryModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  categoryModalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '70%',
  },
  categoryModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  categoryModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  categoryCloseButton: {
    padding: 8,
  },
  categoryCloseButtonText: {
    fontSize: 20,
    color: '#666',
  },
  categoryList: {
    padding: 12,
  },
  categoryItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginVertical: 4,
  },
  categoryItemSelected: {
    backgroundColor: '#ECFFDC',
  },
  categoryItemText: {
    fontSize: 15,
    color: '#333',
  },
  categoryItemTextSelected: {
    color: '#4CAF50',
    fontWeight: '600',
  },
  tabIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  input: {
    flex: 1,
    fontSize: 17,
    height: 48,
    padding: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    marginRight: 10,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F5F5F5',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginBottom: 2,
    marginTop: 1,
  },
  categoryBadgeText: {
    fontSize: 10,
    color: '#666',
    fontWeight: 'bold',
  },
  actionIconContainer: {
    marginRight: 8,
  },
  categoryButtonSelected: {
    backgroundColor: '#222',
    borderColor: '#222',
  },
  categoryButtonTextSelected: {
    color: '#fff',
    fontWeight: 'bold',
  },
  fab: {
    position: 'absolute',
    right: 24,
    bottom: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 100,
  },
  hostNameText: {
    fontSize: 13,
    color: '#222',
    fontWeight: '500',
    marginLeft: 6,
  },
  studyDescription: {
    fontSize: 13,
    color: '#666',
    marginTop: 6,
    marginBottom: 4,
  },
  adContainer: {
    height: 130,
    marginHorizontal: 12,
    marginTop: -10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 14,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  jobSectionContainer: {
    marginVertical: 20,
    marginHorizontal: 20,
  },
  jobScroll: {
    marginTop: 12,
  },
  jobCard: {
    width: 280,
    marginRight: 12,
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  jobImage: {
    width: '100%',
    height: 160,
    backgroundColor: '#f0f0f0',
  },
  jobContent: {
    padding: 16,
  },
  jobTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
    lineHeight: 22,
  },
  jobCompanyName: {
    fontSize: 14,
    color: '#666',
    fontWeight: '400',
  },
  formGroup: {
    marginBottom: 16,
  },
});

