/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ImageSplash`; params?: Router.UnknownInputParams; } | { pathname: `/study`; params?: Router.UnknownInputParams; } | { pathname: `/study/types`; params?: Router.UnknownInputParams; } | { pathname: `/study/utils/getAttendanceImage`; params?: Router.UnknownInputParams; } | { pathname: `/study/utils/getCategoryLabel`; params?: Router.UnknownInputParams; } | { pathname: `/study/hooks/useApiBaseUrl`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/dating`; params?: Router.UnknownInputParams; } | { pathname: `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/record`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ImageSplash`; params?: Router.UnknownOutputParams; } | { pathname: `/study`; params?: Router.UnknownOutputParams; } | { pathname: `/study/types`; params?: Router.UnknownOutputParams; } | { pathname: `/study/utils/getAttendanceImage`; params?: Router.UnknownOutputParams; } | { pathname: `/study/utils/getCategoryLabel`; params?: Router.UnknownOutputParams; } | { pathname: `/study/hooks/useApiBaseUrl`; params?: Router.UnknownOutputParams; } | { pathname: `/user`; params?: Router.UnknownOutputParams; } | { pathname: `/dating`; params?: Router.UnknownOutputParams; } | { pathname: `/schedule`; params?: Router.UnknownOutputParams; } | { pathname: `/record`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/ImageSplash${`?${string}` | `#${string}` | ''}` | `/study${`?${string}` | `#${string}` | ''}` | `/study/types${`?${string}` | `#${string}` | ''}` | `/study/utils/getAttendanceImage${`?${string}` | `#${string}` | ''}` | `/study/utils/getCategoryLabel${`?${string}` | `#${string}` | ''}` | `/study/hooks/useApiBaseUrl${`?${string}` | `#${string}` | ''}` | `/user${`?${string}` | `#${string}` | ''}` | `/dating${`?${string}` | `#${string}` | ''}` | `/schedule${`?${string}` | `#${string}` | ''}` | `/record${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/ImageSplash`; params?: Router.UnknownInputParams; } | { pathname: `/study`; params?: Router.UnknownInputParams; } | { pathname: `/study/types`; params?: Router.UnknownInputParams; } | { pathname: `/study/utils/getAttendanceImage`; params?: Router.UnknownInputParams; } | { pathname: `/study/utils/getCategoryLabel`; params?: Router.UnknownInputParams; } | { pathname: `/study/hooks/useApiBaseUrl`; params?: Router.UnknownInputParams; } | { pathname: `/user`; params?: Router.UnknownInputParams; } | { pathname: `/dating`; params?: Router.UnknownInputParams; } | { pathname: `/schedule`; params?: Router.UnknownInputParams; } | { pathname: `/record`; params?: Router.UnknownInputParams; };
    }
  }
}
